# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46ace7f693831d4624269e923a93e2e4729951457c8dac6a9c3d5fc1709a8b61ccc33131a8c428d1d33aa42059dab87aad539c49fba74773c21564ec449b0fc9

test:
  secret_key_base: 4e2d43359f49a49660b981482744dbd21c08d47e1f51573d877e67ae0abbb9f4d8692c1a3c94393eee73496bcbda8295508a6a432603ed25b056a861e7e20bd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
